//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.20 at 10:47:26 AM EET 
//


package XML;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the XML package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _History_QNAME = new QName("", "history");

    public ObjectFactory() {
    }

   
    public HistoryType createHistoryType() {
        return new HistoryType();
    }


    public MessageType createMessageType() {
        return new MessageType();
    }

    @XmlElementDecl(namespace = "", name = "history")
    public JAXBElement<HistoryType> createHistory(HistoryType value) {
        return new JAXBElement<HistoryType>(_History_QNAME, HistoryType.class, null, value);
    }

}
